loom {
    accessWidenerPath = file("src/main/resources/the_alterworld.accesswidener")
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

dependencies {
    common(project(path: ':core', configuration: 'namedElements')) { transitive false }
    common(project(path: ':architects-assembly', configuration: 'namedElements')) { transitive false }
    common(project(path: ':flora-and-fauna', configuration: 'namedElements')) { transitive false }
    common(project(path: ':swords-and-shields', configuration: 'namedElements')) { transitive false }
    common(project(path: ':chilling-peaks', configuration: 'namedElements')) { transitive false }
}